name: Test

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  mac:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-10.15
          - macos-11
        otp:
          - 23
          - 24
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Configure Homebrew cache
        uses: actions/cache@v2
        with:
          path: |
            ~/Library/Caches/Homebrew/
            ~/Library/Caches/Homebrew/downloads/
          key: brew-${{ matrix.os }}-${{ matrix.otp  }}
      - name: prepare
        run: |
          brew update
          brew install erlang@${{ matrix.otp }}
          brew install automake
          brew install bison
      - name: release build
        run: |
          export PATH="/usr/local/opt/bison/bin:$PATH"
          export PATH="/usr/local/opt/erlang@${{ matrix.otp }}/bin:$PATH"
          ${GITHUB_WORKSPACE}/rebar3 eunit
  linux:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        erl_otp:
          - 23.3.4.9-4
          - 24.2.1-1
        elixir:
          - 1.13.3
        os:
          - ubuntu20.04
          - ubuntu18.04
          - ubuntu16.04
          - debian10
          - debian9
          - el7
          - el8

    steps:
    - uses: actions/checkout@v1
    - run: |
        IMAGE=ghcr.io/emqx/emqx-builder/5.0-15:${{ matrix.elixir }}-${{ matrix.erl_otp }}-${{ matrix.os }}
        docker run --rm -i -v ${GITHUB_WORKSPACE}:/wd --workdir /wd $IMAGE bash -euc './rebar3 eunit'
