name: Test

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        erl_otp:
          - 23.3.4.9-4
          - 24.2.1-1
        elixir:
          - 1.13.3
        os:
          - ubuntu20.04
          - ubuntu18.04
          - ubuntu16.04
          - debian10
          - debian9
          - rockylinux8

    container: "ghcr.io/emqx/emqx-builder/5.0-9:${{ matrix.elixir }}-${{ matrix.erl_otp }}-${{ matrix.os }}"

    steps:
    - uses: actions/checkout@v2
    - run: ${GITHUB_WORKSPACE}/rebar3 eunit
