name: Test

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  mac:
    strategy:
      fail-fast: false
      matrix:
        otp:
          - 25.3.2-1
        os:
          - macos-12-arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/macos-erlang
        with:
          otp: ${{ matrix.otp }}
          os: ${{ matrix.os }}
      - run: |
          . $HOME/.kerl/${{ matrix.otp }}/activate
          ./build.sh
          rebar3 eunit

  linux:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        builder:
          - 5.1-3
        otp:
          - 25.3.2-1
        elixir:
          - 1.14.5
        os:
          - ubuntu22.04

    container: ghcr.io/emqx/emqx-builder/${{ matrix.builder }}:${{ matrix.elixir }}-${{ matrix.otp }}-${{ matrix.os }} 

    steps:
      - uses: actions/checkout@v3
      - run: ./build.sh
      - run: rebar3 eunit
