name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      branch_or_tag:
        required: false
      is_release:
        required: false
        default: false

jobs:
  mac:
    strategy:
      fail-fast: false
      matrix:
        otp:
          - 24
          - 25
        os:
          - macos-11
          - macos-12
          - macos-12-arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch_or_tag }} # when input is not given, the event tag is used

      - name: Configure Homebrew cache
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/Homebrew/
            ~/Library/Caches/Homebrew/downloads/
          key: brew-${{ matrix.os }}-${{ matrix.otp  }}

      - name: prepare
        run: |
          # See https://github.com/actions/setup-python/issues/577
          # brew update
          brew install curl zip unzip gnu-sed automake bison
          brew install erlang@${{ matrix.otp }}
          echo "$(brew --prefix bison)/bin" >> $GITHUB_PATH
          echo "$(brew --prefix erlang@${{ matrix.otp }})/bin" >> $GITHUB_PATH
          git config --global credential.helper store

      - name: build
        if: ! startsWith(github.ref, 'refs/tags/') || inputs.is_release == false
        run: |
          ./build.sh

      - name: build release
        if: startsWith(github.ref, 'refs/tags/') || inputs.is_release == true
        run: |
          env BUILD_RELEASE=1 ./build.sh

      - uses: actions/upload-artifact@v3
        if: startsWith(github.ref, 'refs/tags/') || inputs.is_release == true
        with:
          name: packages
          path: |
            _packages/*.tar.gz
            _packages/*.tar.gz.sha256

  linux:
    strategy:
      fail-fast: false
      matrix:
        builder:
          - 5.0-32
        otp:
          - 24.3.4.2-2
          - 25.1.2-2
        elixir:
          - 1.13.4
        arch:
          - amd64
          - arm64
        os:
          - ubuntu22.04
          - ubuntu20.04
          - ubuntu18.04
          - ubuntu16.04
          - debian11
          - debian10
          - debian9
          - amzn2
          - el7
          - el8
          - el9
          - alpine3.15.1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch_or_tag }} # when input is not given, the event tag is used

      - uses: docker/setup-buildx-action@v2

      - uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ matrix.arch }}

      - name: build
        if: ! startsWith(github.ref, 'refs/tags/') || inputs.is_release == false
        run: |
          IMAGE=ghcr.io/emqx/emqx-builder/${{ matrix.builder }}:${{ matrix.elixir }}-${{ matrix.otp }}-${{ matrix.os }}
          docker run -i --rm --user 1001 -v $(pwd):/wd --workdir /wd --platform=linux/${{ matrix.arch }} $IMAGE bash -euc './build.sh'

      - name: build release
        if: startsWith(github.ref, 'refs/tags/') || inputs.is_release == true
        run: |
          IMAGE=ghcr.io/emqx/emqx-builder/${{ matrix.builder }}:${{ matrix.elixir }}-${{ matrix.otp }}-${{ matrix.os }}
          docker run -i --rm --user 1001 -v $(pwd):/wd --workdir /wd --platform=linux/${{ matrix.arch }} -e BUILD_RELEASE=1 $IMAGE bash -euc './build.sh'

      - uses: actions/upload-artifact@v3
        if: startsWith(github.ref, 'refs/tags/') || inputs.is_release == true
        with:
          name: packages
          path: |
            _packages/*.tar.gz
            _packages/*.tar.gz.sha256

  release:
    runs-on: ubuntu-latest
    needs:
      - mac
      - linux
    if: startsWith(github.ref, 'refs/tags/') || inputs.is_release == true
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: packages
          path: packages
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Erlang jq NIF ${{ github.ref_name }} Released
          files: "packages/*"
          draft: false
          prerelease: false
